# This is a basic workflow to help you get started with Actions
name: CI

# Triggers the workflow on push or pull request events
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: install required packages for puppeteer
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: npm install, bundle, and test
        run: |
          npm install
          npm run clean:bundles
          npm run bundle
          npm test
        env:
          CI: true
